<?php
require_once __DIR__ . '../../../init.php';

require HANDLERS_PATH . '/profilefetch.php';

if($profile) {
    $username = $profile['user_username'];
    $avatar = $profile['user_avatar'];
    $info = $profile['user_info'];
}

?>
<div class="profileView">
    <h2>Profile</h2>
    <div>
    <?php if($profile): ?> 
    <img src="<?php echo $avatar ?>" alt="user_avatar" />
    <div>
        <h3><?php echo $username ?></h3>
        <a href="/Promptr/pages/publicProfilePage.php?profile=<?php echo $username ?>"><?php echo 'Promptr/'.$username ?></a>
        <p>
        <?php
        if(!empty($info) || $info !== null) {
            if(strpos($info, '#') !== false) {
                $words = explode(' ', $info);
    
                foreach($words as $word) {
                    if(strpos($word, '#') === 0) {
                        echo '<strong style="color: #6861fc; font-family: monospace;">' . $word . ' </strong>';
                    } else {
                        echo $word . ' ';
                    }
                }
            } else {
                echo $info;
            }
        }
        ?>
        </p>
    </div>
    <?php endif; 
    ?>
    
    </div>

<h2>Latest Prompts</h2>
<div id="latestPrompts">
    <?php  
    if($prompts): 
    ?>
        <?php foreach($prompts as $prompt) {
            echo '<p>added prompt on: <strong>' . date( 'd F Y g:i A', strtotime($prompt['prompt_date'])). '</strong></p>';
            echo '<p>Prompt used: <code style="background-color: #f7f7f7; padding: 0.5rem; border-radius: 0.5rem">' . $prompt['prompt_text'] . '</code></p>';
            echo '<img src="'. $prompt['prompt_img_src'] .'" alt="prompt image" width=400 />';
        } 
    
    else:
        echo '<h2 style="margin: auto; color: lightgray;">No Prompts generated by this user</h2>';

        ?>  
    <?php endif; ?>
    </div>
</div>




